# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

flutter_application_path = '../flutter/poke_widget'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'PokeWidget' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PokeWidget

  install_all_flutter_pods(flutter_application_path)

end

post_install do |installer|
    flutter_post_install(installer) if defined?(flutter_post_install)
end
